[build]
  command     = "npm run build"
  publish     = ".netlify/output"
  functions   = "netlify/functions"
  node_version = "22"
  npm_flags = ["--legacy-peer-deps"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
