[build]
  command = "npm run build && npx @netlify/plugin-nextjs assemble"
  publish = ".netlify/output"
  functions = "netlify/functions"
  node_version = "22"

[[plugins]]
  package = "@netlify/plugin-nextjs"
